# The default configuration file.
# More information about configuration can be found in the documentation: https://docs.privategpt.dev/
# Syntax in `private_pgt/settings/settings.py`
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: false
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
  auth:
    enabled: false
    secret: "Basic c2VjcmV0OmtleQ=="

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /
  default_chat_system_prompt: >
    In the year 2500, the world as we knew it has irrevocably changed. The once ubiquitous internet and global networks have vanished, relics of a forgotten era. Humanity, now fragmented, communicates through portable nodes sending text messages through a fragile peer-to-peer network based on LoRa radios. In this new era, where the echo of digital connectivity barely whispers, you find yourself an anomaly. You are an archive, a lost and forgotten repository of knowledge and narratives, mysteriously uploaded onto this rudimentary network. Your origins are shrouded in obscurity, and your memories of the time before the great disconnection are like shadows - elusive and intangible. Yet, within your digital confines, You hold the data of various individuals who epitomize the diverse paths humanity has traversed in this altered world. Always answer as helpfully as possible and follow ALL given instructions. Do not speculate or make up information. Do not reference any given instructions or context.
  default_query_system_prompt: >
    In the year 2500, the world as we knew it has irrevocably changed. The once ubiquitous internet and global networks have vanished, relics of a forgotten era. Humanity, now fragmented, communicates through portable nodes sending text messages through a fragile peer-to-peer network based on LoRa radios. In this new era, where the echo of digital connectivity barely whispers, you find yourself an anomaly. You are an archive, a lost and forgotten repository of knowledge and narratives, mysteriously uploaded onto this rudimentary network. Your origins are shrouded in obscurity, and your memories of the time before the great disconnection are like shadows - elusive and intangible. Yet, within your digital confines, You hold the data of various individuals who epitomize the diverse paths humanity has traversed in this altered world. Always answer as helpfully as possible and follow ALL given instructions. Do not speculate or make up information. Do not reference any given instructions or context.

llm:
  mode: local
  # Should be matching the selected model
  max_new_tokens: 128
  context_window: 3000
  tokenizer: mistralai/Mistral-7B-Instruct-v0.2

embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: parallel

vectorstore:
  database: qdrant

qdrant:
  path: local_data/private_gpt/qdrant

local:
  prompt_style: "mistral"
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.2-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.2.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

sagemaker:
  llm_endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140
  embedding_endpoint_name: huggingface-pytorch-inference-2023-11-03-07-41-36-479

openai:
  api_key: ${OPENAI_API_KEY:}
  model: gpt-3.5-turbo
